### ISSUE TITLE
Header refinement

### ISSUE THREAD

**Issue by zyrrus** [zyrrus/parallel#3]
# To-do

- [ ] create dropdown menus for nav links that need them
- [ ] middle nav link section is not properly centered
- [ ] make it responsive
